// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFISgPsDFxFJadwDSHrbkQ47bQchXpfY',
    appId: '1:653289926049:web:c533c9d79e48656b572fe0',
    messagingSenderId: '653289926049',
    projectId: 'idea-organizer-afc78',
    authDomain: 'idea-organizer-afc78.firebaseapp.com',
    storageBucket: 'idea-organizer-afc78.firebasestorage.app',
    measurementId: 'G-DNMDX8T1XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8l_K1rz3nPoWfGtaQIrSxGZmNzvNrvNg',
    appId: '1:653289926049:android:513a03402727afdf572fe0',
    messagingSenderId: '653289926049',
    projectId: 'idea-organizer-afc78',
    storageBucket: 'idea-organizer-afc78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKubqrtSyA6iZwGumMhhGj06RHAZKQ5g8',
    appId: '1:653289926049:ios:b53d4289eef19120572fe0',
    messagingSenderId: '653289926049',
    projectId: 'idea-organizer-afc78',
    storageBucket: 'idea-organizer-afc78.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKubqrtSyA6iZwGumMhhGj06RHAZKQ5g8',
    appId: '1:653289926049:ios:b53d4289eef19120572fe0',
    messagingSenderId: '653289926049',
    projectId: 'idea-organizer-afc78',
    storageBucket: 'idea-organizer-afc78.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGFISgPsDFxFJadwDSHrbkQ47bQchXpfY',
    appId: '1:653289926049:web:be127cf6bfcfb6d5572fe0',
    messagingSenderId: '653289926049',
    projectId: 'idea-organizer-afc78',
    authDomain: 'idea-organizer-afc78.firebaseapp.com',
    storageBucket: 'idea-organizer-afc78.firebasestorage.app',
    measurementId: 'G-3ZTKWBM3FR',
  );
}